services:

  database:
    container_name: postgres_product_service_cont
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: product_service_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5001:5432"

  app:
    build: .
    container_name: 'product-app'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/product_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
       - "9393:9393"
    depends_on:
      - database