server:
  port: 9393

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/product_service_db
#    url: jdbc:postgresql://localhost:5432/product_service_db
    username: postgres
    password: postgres

  liquibase:
    change-log: db/changelog/liquibase-master.yaml
    enabled: true

  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui
