services:

  redis:
    image: redis:latest
    container_name: redis-cont
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  app:
    build: .
    container_name: 'number-generate-app'
    ports:
       - "9191:9191"
    depends_on:
      - redis
